- hosts: slave1
  become: yes
  name: Installing apache2 on slave1
  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: latest

- hosts: slave2
  become: yes
  name: Install nginx on slave2
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: latest

- hosts: slave3
  become: yes
  name: Install the apache2
  tasks:
    - name: Install the apache2
      apt: 
        name: apache2
        state: latest
